name: Elixir CI
on: [pull_request]

permissions:
    contents: read

jobs:
    elixir-test:
        name: Test Elixir
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: Wandalen/wretry.action@v3.8.0
              with:
                  action: actions/checkout@v4
                  attempt_limit: 3
                  # attempt_delay in ms
                  attempt_delay: 5000

            - name: Install devbox
              uses: jetify-com/devbox-install-action@v0.13.0

            - name: Run CI (test and format)
              run: devbox run ci
